<h1>Alphalives Test - Zf2 Template</h1>
<h2>AlmUser</h2>
<ul>	
	<li><a href="<?php echo $this->url('zfcuser/login'); ?>">Connection</a></li>
    <li><a href="<?php echo $this->url('zfcuser/register'); ?>">Inscription</a></li>
    <li><a href="<?php echo $this->url('alphalives-test/secuRessource'); ?>">Page sécu Ressource</a></li>
    <li><a href="<?php echo $this->url('alphalives-test/secu1'); ?>">Page sécu 1</a></li>
    <li><a href="<?php echo $this->url('alphalives-test/secu2'); ?>">Page sécu 2</a></li>
</ul>

<h2>AlmBase</h2>
<ul>	
	<li><a href="<?php echo $this->url('zfcadmin'); ?>">Administration</a></li>
</ul>

<h2>Gestion des erreurs</h2>
<ul>	
	<li><a href="<?php echo $this->url('alphalives-test/error'); ?>">Déclanchement erreur</a></li>
</ul>